Enhancement/Datepicker for Web
CareLuLu/react-native-web-ui-components pull request #395
Opened 2021-05-19 18:35 UTC by carelulu-kenneth

**Summary**
* Updated css for datepicker for web

This PR fixes/implements the following **bugs/features**
* [ ] Feature uses month and year dropdown

**Test plan (required)**
![time-final](https://user-images.githubusercontent.com/82450059/118864821-ef48af00-b912-11eb-9137-e6a26b7730c0.gif)
![date-final](https://user-images.githubusercontent.com/82450059/118864833-f1ab0900-b912-11eb-998a-8d5b3afbec47.gif)

**Closing issues**
closes https://github.com/CareLuLu/v3-app/issues/1427

2021-05-20 14:41 UTC, carelulu-kevin reviewed
Thanks for working on this @carelulu-kenneth. Please see my comment.

2021-05-20 14:41 UTC, carelulu-kevin commented on src/Datepicker/index.web.js
> +        showYearDropdown
Let's allow this prop `showMonthDropdown` and `showYearDropdown` to be configurable. Add this to https://github.com/CareLuLu/react-native-web-ui-components/blob/7d459f8348f6a3f6e33539ba91018a6cb3f019dc/src/Datepicker/index.web.js#L298 and set default to `true` https://github.com/CareLuLu/react-native-web-ui-components/blob/7d459f8348f6a3f6e33539ba91018a6cb3f019dc/src/Datepicker/index.web.js#L318.

2021-05-24 19:10 UTC, CareLuLu-Gabriel approved these changes
Great job, @carelulu-kenneth! LGTM!

2021-06-02 16:16 UTC, carelulu-igor approved these changes
Good job @carelulu-kenneth!

2021-06-02 16:26 UTC, carelulu-kevin requested changes
@carelulu-kenneth please check this part of the css. currently, it's not visible with a white background.

```css
.react-datepicker__day{cu.react-datepicker__navigation--nextnd-color:#3dcc4a;color:#fff}
```

![Screen Shot 2021-06-03 at 12 22 11 AM](https://user-images.githubusercontent.com/54905174/120516326-cf7cb500-c401-11eb-8a3d-77756ce3c106.png)

![Screen Shot 2021-06-03 at 12 22 21 AM](https://user-images.githubusercontent.com/54905174/120516333-d1df0f00-c401-11eb-915c-6f6b1ed8da3d.png)

2021-06-02 16:29 UTC, merged